In [1]:
vals = [1584, 1656.5, 1629.8, 1712, 1647, 1736,
       1681, 1757, 1689, 1730, 1697, 1809, 1789, 1840,
       1867, 1930, 1865, 1885, 1914, 1932, 1894, 1891,
       1965, 1946, 1939, 2061, 1962, 2296, 2029, 2080,
       1974, 2083, 1949, 2007, 2090, 2081, 2117, 2149,
       2105, 2326, 2050, 2140, 2342, 2163, 2207, 2239,
       2236, 2343, 2290, 2380, 2350, 2538, 2416, 2397,
       2564, 2407, 2562, 2407, 2403, 2592, 2507, 2501,
       2448, 2619, 2626, 2694, 2476, 2548, 2540, 2486,
       2523, 2638, 2485, 2733, 2555, 2753, 2654, 2643,
       2797, 2692, 2655, 2518, 2710, 2767, 2741, 2907,
       2787, 3018, 2936, 2711, 2870, 2985, 2945, 2884,
       3038, 3028, 3053, 3197, 3082, 3430, 3157, 3274,
       3113, 3225, 3020, 3104, 3217, 3174, 3207, 3241,
       3181, 3581, 3345, 3301, 3550, 3258, 3320, 3291,
       3171, 3501, 3443, 3367, 3408, 3528, 3636, 3476,
       3717, 3555, 3547, 3609, 3530, 3844, 3704, 3808,
       3701, 4090, 3865, 3954, 4107, 3917, 3934, 3713,
       3871, 4103, 4125, 4290, 3982, 4425, 4240, 4059,
       4204, 4256, 4268, 4050, 4291, 4276, 4272, 4440]

Media = soma / n

In [5]:
soma = 0

for i in range(len(vals)):
    soma += vals[i]

media = soma/(len(vals))
media

2831.2424050632912

Variancia (desvio pd)² = [soma(x-media)²] / n

In [6]:
var = 0

for i in vals:
    var += (i - media)**2

variancia = var/len(vals)
variancia

599180.1671258612

# Numpy

In [7]:
import numpy as np

In [12]:
lista = [1, 2, 3]
np_lista = np.array(lista)
print(np_lista)
print(lista)

[1 2 3]
[1, 2, 3]


In [13]:
np_lista[-1]

3

In [14]:
type(vals)

list

In [17]:
np_vals = np.array(vals)
np_vals

array([1584. , 1656.5, 1629.8, 1712. , 1647. , 1736. , 1681. , 1757. ,
       1689. , 1730. , 1697. , 1809. , 1789. , 1840. , 1867. , 1930. ,
       1865. , 1885. , 1914. , 1932. , 1894. , 1891. , 1965. , 1946. ,
       1939. , 2061. , 1962. , 2296. , 2029. , 2080. , 1974. , 2083. ,
       1949. , 2007. , 2090. , 2081. , 2117. , 2149. , 2105. , 2326. ,
       2050. , 2140. , 2342. , 2163. , 2207. , 2239. , 2236. , 2343. ,
       2290. , 2380. , 2350. , 2538. , 2416. , 2397. , 2564. , 2407. ,
       2562. , 2407. , 2403. , 2592. , 2507. , 2501. , 2448. , 2619. ,
       2626. , 2694. , 2476. , 2548. , 2540. , 2486. , 2523. , 2638. ,
       2485. , 2733. , 2555. , 2753. , 2654. , 2643. , 2797. , 2692. ,
       2655. , 2518. , 2710. , 2767. , 2741. , 2907. , 2787. , 3018. ,
       2936. , 2711. , 2870. , 2985. , 2945. , 2884. , 3038. , 3028. ,
       3053. , 3197. , 3082. , 3430. , 3157. , 3274. , 3113. , 3225. ,
       3020. , 3104. , 3217. , 3174. , 3207. , 3241. , 3181. , 3581. ,
      

In [22]:
media = np.mean(np_vals)
media

2831.2424050632912

In [21]:
desvio_pd = np.std(np_vals)
desvio_pd

774.0672885000769

Um `np.array` não é necessariamente igual a uma lista. 

Uma das principais diferenças é que os elementos de um vetor devem ser do **mesmo** tipo.

In [23]:
np_vals

array([1584. , 1656.5, 1629.8, 1712. , 1647. , 1736. , 1681. , 1757. ,
       1689. , 1730. , 1697. , 1809. , 1789. , 1840. , 1867. , 1930. ,
       1865. , 1885. , 1914. , 1932. , 1894. , 1891. , 1965. , 1946. ,
       1939. , 2061. , 1962. , 2296. , 2029. , 2080. , 1974. , 2083. ,
       1949. , 2007. , 2090. , 2081. , 2117. , 2149. , 2105. , 2326. ,
       2050. , 2140. , 2342. , 2163. , 2207. , 2239. , 2236. , 2343. ,
       2290. , 2380. , 2350. , 2538. , 2416. , 2397. , 2564. , 2407. ,
       2562. , 2407. , 2403. , 2592. , 2507. , 2501. , 2448. , 2619. ,
       2626. , 2694. , 2476. , 2548. , 2540. , 2486. , 2523. , 2638. ,
       2485. , 2733. , 2555. , 2753. , 2654. , 2643. , 2797. , 2692. ,
       2655. , 2518. , 2710. , 2767. , 2741. , 2907. , 2787. , 3018. ,
       2936. , 2711. , 2870. , 2985. , 2945. , 2884. , 3038. , 3028. ,
       3053. , 3197. , 3082. , 3430. , 3157. , 3274. , 3113. , 3225. ,
       3020. , 3104. , 3217. , 3174. , 3207. , 3241. , 3181. , 3581. ,
      

In [25]:
vals_2000 = np_vals > 2000
vals_2000

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [27]:
np.sum(vals_2000) #soma os verdadeiros (V = 1, F = 0)

130

In [30]:
np_vals[-20:]

array([4107., 3917., 3934., 3713., 3871., 4103., 4125., 4290., 3982.,
       4425., 4240., 4059., 4204., 4256., 4268., 4050., 4291., 4276.,
       4272., 4440.])

In [31]:
np_vals[0:2]

array([1584. , 1656.5])

In [29]:
np_vals[vals_2000] #Filtrar

array([2061., 2296., 2029., 2080., 2083., 2007., 2090., 2081., 2117.,
       2149., 2105., 2326., 2050., 2140., 2342., 2163., 2207., 2239.,
       2236., 2343., 2290., 2380., 2350., 2538., 2416., 2397., 2564.,
       2407., 2562., 2407., 2403., 2592., 2507., 2501., 2448., 2619.,
       2626., 2694., 2476., 2548., 2540., 2486., 2523., 2638., 2485.,
       2733., 2555., 2753., 2654., 2643., 2797., 2692., 2655., 2518.,
       2710., 2767., 2741., 2907., 2787., 3018., 2936., 2711., 2870.,
       2985., 2945., 2884., 3038., 3028., 3053., 3197., 3082., 3430.,
       3157., 3274., 3113., 3225., 3020., 3104., 3217., 3174., 3207.,
       3241., 3181., 3581., 3345., 3301., 3550., 3258., 3320., 3291.,
       3171., 3501., 3443., 3367., 3408., 3528., 3636., 3476., 3717.,
       3555., 3547., 3609., 3530., 3844., 3704., 3808., 3701., 4090.,
       3865., 3954., 4107., 3917., 3934., 3713., 3871., 4103., 4125.,
       4290., 3982., 4425., 4240., 4059., 4204., 4256., 4268., 4050.,
       4291., 4276.,

In [34]:
np_maior_2000 = np_vals[np_vals>2000][::-1]

np_maior_2000

array([4440., 4272., 4276., 4291., 4050., 4268., 4256., 4204., 4059.,
       4240., 4425., 3982., 4290., 4125., 4103., 3871., 3713., 3934.,
       3917., 4107., 3954., 3865., 4090., 3701., 3808., 3704., 3844.,
       3530., 3609., 3547., 3555., 3717., 3476., 3636., 3528., 3408.,
       3367., 3443., 3501., 3171., 3291., 3320., 3258., 3550., 3301.,
       3345., 3581., 3181., 3241., 3207., 3174., 3217., 3104., 3020.,
       3225., 3113., 3274., 3157., 3430., 3082., 3197., 3053., 3028.,
       3038., 2884., 2945., 2985., 2870., 2711., 2936., 3018., 2787.,
       2907., 2741., 2767., 2710., 2518., 2655., 2692., 2797., 2643.,
       2654., 2753., 2555., 2733., 2485., 2638., 2523., 2486., 2540.,
       2548., 2476., 2694., 2626., 2619., 2448., 2501., 2507., 2592.,
       2403., 2407., 2562., 2407., 2564., 2397., 2416., 2538., 2350.,
       2380., 2290., 2343., 2236., 2239., 2207., 2163., 2342., 2140.,
       2050., 2326., 2105., 2149., 2117., 2081., 2090., 2007., 2083.,
       2080., 2029.,

In [36]:
copiar = np.copy(np_maior_2000[20:])
copiar

array([3954., 3865., 4090., 3701., 3808., 3704., 3844., 3530., 3609.,
       3547., 3555., 3717., 3476., 3636., 3528., 3408., 3367., 3443.,
       3501., 3171., 3291., 3320., 3258., 3550., 3301., 3345., 3581.,
       3181., 3241., 3207., 3174., 3217., 3104., 3020., 3225., 3113.,
       3274., 3157., 3430., 3082., 3197., 3053., 3028., 3038., 2884.,
       2945., 2985., 2870., 2711., 2936., 3018., 2787., 2907., 2741.,
       2767., 2710., 2518., 2655., 2692., 2797., 2643., 2654., 2753.,
       2555., 2733., 2485., 2638., 2523., 2486., 2540., 2548., 2476.,
       2694., 2626., 2619., 2448., 2501., 2507., 2592., 2403., 2407.,
       2562., 2407., 2564., 2397., 2416., 2538., 2350., 2380., 2290.,
       2343., 2236., 2239., 2207., 2163., 2342., 2140., 2050., 2326.,
       2105., 2149., 2117., 2081., 2090., 2007., 2083., 2080., 2029.,
       2296., 2061.])

1. Escreva um programa para criar um array Numpy e encontrar os índices de todos os elementos iguais a um valor específico.

In [42]:
lista = [1,0,1,2,5,6]
x = np.array(lista)
x



array([1, 0, 1, 2, 5, 6])

2. Escreva um programa para criar um array Numpy e extrair todos os elementos maiores que um valor específico usando slicing e masking.

In [51]:
x[x > 1]

array([2, 5, 6])

3. Escreva um programa para criar um array Numpy e usar indexação para extrair elementos em uma linha e coluna específicas.

In [44]:
x[1:]

array([0, 1, 2, 5, 6])

4. Escreva um programa para criar um array Numpy e calcular a soma de todos os elementos maiores que um valor específico.

In [45]:
np.sum(x)

15

5. Escreva um programa que faça a soma de todos os elementos pares de um numpy array. 

In [52]:
print(x[x % 2 == 0])
np.sum(x[x % 2 == 0])

[0 2 6]


8

6. Escreva um programa que readeque todos os valores de um array Numpy entre 0 e 5. Para isso, valores menores que 0 devem ser substituídos por 0, e valores maiores que 5 devem ser substituídas por 5.

In [49]:
x_1 = np.copy(x)
x_1



array([1, 0, 1, 2, 5, 6])