In [16]:
import numpy as np

x = np.random.randint(0, 100, size=10)
np.sort(x)

array([ 2, 41, 45, 48, 64, 72, 76, 85, 87, 95])

In [21]:
y = np.arange(1,10,1)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
y_new = y.reshape(3,3)
y_new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
y_new2 = y_new % 2 == 0
y_new2
y_par = y_new[y_new2]
y_par

array([2, 4, 6, 8])

In [30]:
np.sum(y_par)

20

In [31]:
np.mean(y_par)

5.0

In [34]:
np.std(y_par)

2.23606797749979