In [1]:
import numpy as np

In [12]:
arr = np.array(42) #0D
arr

array(42)

In [11]:
lista = [1,2,3,4,5] #1D
lista = np.array(lista)
lista

array([1, 2, 3, 4, 5])

In [13]:
lista_2d = [[1,2,3],[4,5,6]] #2D
lista_2d = np.array(lista_2d)
lista_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
lista_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3D
lista_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# numero de dimensões


In [17]:
lista_2d.ndim

2

In [18]:
lista_3d.ndim

3

In [25]:
arr = np.array([1, 2, 3, 4], ndmin=2)

In [29]:
arr = [[1, 2, 3, 4],[1,2,3,4]]
arr = np.array(arr)
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [20]:
lista

array([1, 2, 3, 4, 5])

In [22]:
lista[2]+lista[3] #operações

7

# slicing - [start:end:step].

In [30]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [31]:
arr[1, 1:4] #array 2, de 1 a 4 elemento

array([2, 3, 4])

In [32]:
arr[0:2, 2] #todas array, terceiro elemento 

array([3, 3])

In [33]:
arr[0:2, 1:4] #todas array, de 1 a 4

array([[2, 3, 4],
       [2, 3, 4]])

# Tipos variavel
* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [34]:
arr.dtype

dtype('int32')

In [35]:
arr.astype('f') #converter tipo

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]], dtype=float32)

# Copy and View

In [36]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Shape


In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


# Reshape


In [42]:
# From 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
# 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
# Pass -1 as the value, and NumPy will calculate this number for you (dimension)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
#multidimensional array to 1D

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# iterate

In [48]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [51]:
# nditer()

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [52]:
for x in np.nditer(arr[:, ::2]): #with step
  print(x)

1
2
5
6


# Enumerated Iteration Using ndenumerate()

In [53]:
arr = np.array([1, 2, 3]) 

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [58]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Concatenate axis = 0 #eixoy =1 #eixox

In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [65]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
# stack - new axis

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [68]:
# hstack() to stack along rows

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [69]:
# vstack()  to stack along columns

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [71]:
# dstack() to stack along height, which is the same as depth

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


# Split

In [72]:
# split

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [73]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Searching Arrays

In [74]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) #return index

print(x)

(array([3, 5, 6], dtype=int64),)


In [75]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [76]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [77]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [78]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# sort (create a copy of array e ordena)

In [79]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [80]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [81]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])